AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  device-service

  SAM Template for device-service

Parameters:
  PrivateSubnets:
    Type: 'AWS::SSM::Parameter::Value<List<String>>'
    Default: /caregem/VpcSubnet
  LambdaSecurityGroupId:
    Type: 'AWS::SSM::Parameter::Value<String>'
    Default: /caregem/VpcSg
  AuthorizerLambdaArn:
    Type: 'AWS::SSM::Parameter::Value<String>'
    Default: /caregem/AuthorizerLambdaArn
  Stage:
    Type: 'AWS::SSM::Parameter::Value<String>'
    Default: /caregem/Stage
  CognitoUserPool:
    Type: 'AWS::SSM::Parameter::Value<String>'
    Default: /caregem/CognitoUserPool
  AwsRegion:
    Type: 'AWS::SSM::Parameter::Value<String>'
    Default: /caregem/AwsRegion
  UserProfileTableName:
    Type: 'AWS::SSM::Parameter::Value<String>'
    Default: /caregem/UserProfileTableName
  MysqlSecret:
    Type: 'AWS::SSM::Parameter::Value<String>'
    Default: /caregem/MysqlSecret
  MlprepMysqlSecret:
    Type: 'AWS::SSM::Parameter::Value<String>'
    Default: /caregem/MlprepMysqlSecret
  AccessLogArn:
    Type: 'AWS::SSM::Parameter::Value<String>'
    Default: /caregem/AccessLogArn
  ApiKeys:
    Type: 'AWS::SSM::Parameter::Value<String>'
    Default: /caregem/ApiKeys
  CaregemS3Config:
    Type: 'AWS::SSM::Parameter::Value<String>'
    Default: /caregem/CaregemS3Config
  MessageSecret:
    Type: 'AWS::SSM::Parameter::Value<String>'
    Default: /caregem/MessageSecret
  UseTwilio:
    Type: 'AWS::SSM::Parameter::Value<String>'
    Default: /caregem/UseTwilio
  TwilioSMSEnabled:
    Type: 'AWS::SSM::Parameter::Value<String>'
    Default: /caregem/TwilioSMSEnabled

Globals:
  Function:
    Timeout: 5
    MemorySize: 512
    Runtime: python3.9
    Architectures:
      - x86_64
    VpcConfig:
      SecurityGroupIds:
        - !Ref LambdaSecurityGroupId
      SubnetIds: !Ref PrivateSubnets
    Environment:
      Variables:
        LOG_LEVEL: 'INFO'
        DB_SECRET_NAME: !Ref MysqlSecret
        MLPREP_SECRET_NAME: !Ref MlprepMysqlSecret
        DYNAMODB_REGION: !Ref AwsRegion
        AWSREGION: !Ref AwsRegion
        USER_POOL_REGION: !Ref AwsRegion
        USER_PROFILE_TABLE_NAME: !Ref UserProfileTableName
        USER_POOL_ID: !Ref CognitoUserPool

  Api:
    EndpointConfiguration: REGIONAL
    TracingEnabled: true
    OpenApiVersion: '2.0'
    Cors:
      AllowMethods: "'OPTIONS,POST,GET,PUT'"
      AllowHeaders: "'Content-Type,Authorization'"
      AllowOrigin: "'*'"

Resources:
  UtilsLayer:
    Type: AWS::Serverless::LayerVersion
    Properties:
      ContentUri: ../layers/utilLayer
      CompatibleRuntimes:
        - python3.9
    Metadata:
      BuildMethod: python3.9
  PatientLayer:
    Type: AWS::Serverless::LayerVersion
    Properties:
      ContentUri: ../layers/patientLayer
      CompatibleRuntimes:
        - python3.9
    Metadata:
      BuildMethod: python3.9
  MessageLayer:
    Type: AWS::Serverless::LayerVersion
    Properties:
      ContentUri: ../layers/messageLayer
      CompatibleRuntimes:
        - python3.9
    Metadata:
      BuildMethod: python3.9

  DeviceApi:
    Type: AWS::Serverless::Api
    Properties:
      StageName: !Ref Stage
      Name: Device Api
      Description: Device Service
      Auth:
        AddDefaultAuthorizerToCorsPreflight: false
        DefaultAuthorizer: LambdaTokenAuthorizer
        Authorizers:
          LambdaTokenAuthorizer:
            FunctionArn: !Ref AuthorizerLambdaArn
      AccessLogSetting:
        DestinationArn: !Ref AccessLogArn
        Format: '{
          "requestTime":"$context.requestTime","requestId":"$context.requestId","httpMethod":"$context.httpMethod", "path":"$context.path", "resourcePath":"$context.resourcePath", "status":"$context.status", "responseLatency":"$context.responseLatency",
          "integrationRequestId":"$context.integration.requestId", "functionResponseStatus":"$context.integration.status", "authorizeResultStatus":"$context.authorize.status", "authorizerServiceStatus":"$context.authorizer.status",
          "authorizerRequestId":"$context.authorizer.requestId","authorizeError":"$context.authorize.error", "claims": "$context.authorizer.claims",
          "ip":"$context.identity.sourceIp", "userAgent":"$context.identity.userAgent", "principalId":"$context.authorizer.principalId", "cognitoUser":"$context.identity.cognitoIdentityId", "user":"$context.identity.user",
          "apiId":"$context.apiId"
        }'

  LambdaRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - lambda.amazonaws.com
            Action: sts:AssumeRole
      Path: /
      Policies:
        - PolicyName: caregem-secret-manager-lambda-policy
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: Allow
                Action:
                  - secretsmanager:GetSecretValue
                Resource: '*'
        - PolicyName: caregem-dynamodb-policy
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: Allow
                Action:
                  - dynamodb:GetItem
                  - dynamodb:Scan
                  - dynamodb:Query
                  - dynamodb:BatchGetItem
                Resource: '*'
        - PolicyName: caregem-s3-lambda-policy
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: Allow
                Action:
                  - s3:GetObject
                Resource: 'arn:aws:s3:::*'
        - PolicyName: caregem-sns-policy
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: Allow
                Action:
                  - 'sns:Publish'
                Resource: '*'
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSLambdaVPCAccessExecutionRole

  DevicePairUnpair:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: DevicePairUnpair
      CodeUri: ./
      Handler: pair_unpair_device.lambda_handler
      Layers:
        - !Ref UtilsLayer
      Role: !GetAtt LambdaRole.Arn
      Events:
        PairDevice:
          Type: Api
          Properties:
            Path: /device/pair_device/{patient_internal_id}
            Method: POST
            RestApiId: !Ref DeviceApi
        UnpairDevice:
          Type: Api
          Properties:
            Path: /device/unpair_device/{patient_internal_id}
            Method: POST
            RestApiId: !Ref DeviceApi

  DevicePairedUsers:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: DevicePairedUsers
      CodeUri: ./
      Handler: paired_users_details.lambda_handler
      Layers:
        - !Ref UtilsLayer
        - !Ref PatientLayer
      Policies:
        - DynamoDBCrudPolicy:
            TableName: '*'
      Role: !GetAtt LambdaRole.Arn
      Events:
        PairedUsers:
          Type: Api
          Properties:
            Path: /device/paired_user/{imei_id}
            Method: GET
            RestApiId: !Ref DeviceApi

  DeviceUnpairedDevices:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: DeviceUnpairedDevices
      CodeUri: ./
      Handler: unpaired_devices.lambda_handler
      Layers:
        - !Ref UtilsLayer
      Role: !GetAtt LambdaRole.Arn
      Events:
        PairedUsers:
          Type: Api
          Properties:
            Path: /device/unpaired_devices/{imei_id}
            Method: GET
            RestApiId: !Ref DeviceApi

  DeviceReading:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: DeviceReadingLambda
      CodeUri: ./
      Handler: device_reading.lambda_handler
      Layers:
        - !Ref UtilsLayer
        - !Ref MessageLayer
      Role: !GetAtt LambdaRole.Arn
      Events:
        DeviceReading:
          Type: Api
          Properties:
            Path: /device/reading/{model_type}
            Method: POST
            RestApiId: !Ref DeviceApi
            Auth:
              Authorizer: 'NONE'
      Environment:
        Variables:
          API_KEYS: !Ref ApiKeys
          ENVIRONMENT: !Ref Stage
          BUCKET_NAME: !Ref CaregemS3Config
          S3_FILE_NAME: caregem_urls.json
          ENCRYPTION_KEY_SECRET_ID: !Ref MessageSecret
          USE_TWILIO: !Ref UseTwilio
          SMS_ENABLED: !Ref TwilioSMSEnabled

Outputs:
  DeviceApi:
    Description: 'API Gateway endpoint URL for NonProd stage for Device Service'
    Value: !Sub 'https://${DeviceApi}.execute-api.${AWS::Region}.amazonaws.com/${Stage}'
