INSERT_SYMPTOM_NOTIFICATION = """INSERT INTO symptom_notifications
            (medical_data_type,
             medical_data_id,
             patient_internal_id,
             notifier_internal_id,
             level,
             notification_details,
             created_on,
             created_by,
             updated_on,
             updated_by,
             notification_status)
VALUES      (%(medical_data_type)s,
             %(medical_data_id)s,
             %(patient_internal_id)s,
             %(notifier_internal_id)s,
             %(level)s,
             %(notification_details)s,
             %(created_on)s,
             %(created_by)s,
             %(updated_on)s,
             %(updated_by)s,
             %(notification_status)s); """

INSERT_MESSAGE_NOTIFICATION = """INSERT INTO message_notifications
            (message_id,
             channel_name,
             notifier_internal_id,
             receiver_internal_id,
             sender_internal_id,
             level,
             notification_details,
             created_on,
             created_by,
             updated_on,
             updated_by,
             notification_status)
VALUES      (%(message_id)s,
             %(channel_name)s,
             %(notifier_internal_id)s,
             %(receiver_internal_id)s,
             %(sender_internal_id)s,
             %(level)s,
             %(notification_details)s,
             %(created_on)s,
             %(created_by)s,
             %(updated_on)s,
             %(updated_by)s,
             %(notification_status)s) 
"""

INSERT_REMOTE_VITAL_NOTIFICATION = """INSERT INTO remote_vital_notifications
            (remote_vital_id,
             patient_internal_id,
             notifier_internal_id,
             level,
             notification_details,
             created_on,
             created_by,
             updated_on,
             updated_by,
             notification_status)
VALUES      (%(remote_vital_id)s,
             %(patient_internal_id)s,
             %(notifier_internal_id)s,
             %(level)s,
             %(notification_details)s,
             %(created_on)s,
             %(created_by)s,
             %(updated_on)s,
             %(updated_by)s,
             %(notification_status)s) 
"""

INSERT_CARE_TEAM_NOTIFICATION = """INSERT INTO care_team_notifications
            (ct_member_internal_id,
             patient_internal_id,
             notifier_internal_id,
             level,
             notification_details,
             created_on,
             created_by,
             updated_on,
             updated_by,
             notification_status)
VALUES      (%(ct_member_internal_id)s,
             %(patient_internal_id)s,
             %(notifier_internal_id)s,
             %(level)s,
             %(notification_details)s,
             %(created_on)s,
             %(created_by)s,
             %(updated_on)s,
             %(updated_by)s,
             %(notification_status)s) 
"""

INSERT_MEDICATION_NOTIFICATION = """INSERT INTO medication_notifications
            (patient_internal_id,
             medication_row_id, 
             notifier_internal_id, 
             level,
             notification_details, 
             created_on, 
             created_by, 
             updated_on, 
             updated_by, 
             notification_status)
VALUES      (%(patient_internal_id)s,
             %(medication_row_id)s,
             %(notifier_internal_id)s,
             %(level)s,
             %(notification_details)s,
             %(created_on)s,
             %(created_by)s,
             %(updated_on)s,
             %(updated_by)s,
              %(notification_status)s); """
