version: 0.2
env:
  git-credential-helper: yes
  CURRENT_COMMIT: $(git rev-parse HEAD)
  PREVIOUS_COMMIT: $(git rev-parse HEAD~1)
phases:
  install:
    runtime-versions:
      python: 3.9
  pre_build:
    commands:
      - echo $SAM_CLI_SOURCE_BUCKET
  build:
    commands:
      - bash backend/build_deploy.sh $CURRENT_COMMIT $PREVIOUS_COMMIT
