AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  network-service

  SAM Template for network-service

Parameters:
  PrivateSubnets:
    Type: 'AWS::SSM::Parameter::Value<List<String>>'
    Default: /caregem/VpcSubnet
  LambdaSecurityGroupId:
    Type: 'AWS::SSM::Parameter::Value<String>'
    Default: /caregem/VpcSg
  AuthorizerLambdaArn:
    Type: 'AWS::SSM::Parameter::Value<String>'
    Default: /caregem/AuthorizerLambdaArn
  Stage:
    Type: 'AWS::SSM::Parameter::Value<String>'
    Default: /caregem/Stage
  CognitoUserPool:
    Type: 'AWS::SSM::Parameter::Value<String>'
    Default: /caregem/CognitoUserPool
  AwsRegion:
    Type: 'AWS::SSM::Parameter::Value<String>'
    Default: /caregem/AwsRegion
  UserProfileTableName:
    Type: 'AWS::SSM::Parameter::Value<String>'
    Default: /caregem/UserProfileTableName
  MysqlSecret:
    Type: 'AWS::SSM::Parameter::Value<String>'
    Default: /caregem/MysqlSecret
  MlprepMysqlSecret:
    Type: 'AWS::SSM::Parameter::Value<String>'
    Default: /caregem/MlprepMysqlSecret
  AccessLogArn:
    Type: 'AWS::SSM::Parameter::Value<String>'
    Default: /caregem/AccessLogArn
  CaregemS3Config:
    Type: 'AWS::SSM::Parameter::Value<String>'
    Default: /caregem/CaregemS3Config
  MessageSecret:
    Type: 'AWS::SSM::Parameter::Value<String>'
    Default: /caregem/MessageSecret
  UseTwilio:
    Type: 'AWS::SSM::Parameter::Value<String>'
    Default: /caregem/UseTwilio
  TwilioSMSEnabled:
    Type: 'AWS::SSM::Parameter::Value<String>'
    Default: /caregem/TwilioSMSEnabled

Globals:
  Function:
    Timeout: 5
    MemorySize: 512
    Runtime: python3.9
    Architectures:
      - x86_64
    VpcConfig:
      SecurityGroupIds:
        - !Ref LambdaSecurityGroupId
      SubnetIds: !Ref PrivateSubnets
    Environment:
      Variables:
        LOG_LEVEL: 'INFO'
        DB_SECRET_NAME: !Ref MysqlSecret
        MLPREP_SECRET_NAME: !Ref MlprepMysqlSecret
        DYNAMODB_REGION: !Ref AwsRegion
        AWSREGION: !Ref AwsRegion
        USER_POOL_REGION: !Ref AwsRegion
        USER_PROFILE_TABLE_NAME: !Ref UserProfileTableName
        USER_POOL_ID: !Ref CognitoUserPool
  Api:
    EndpointConfiguration: REGIONAL
    TracingEnabled: true
    OpenApiVersion: '2.0'
    Cors:
      AllowMethods: "'OPTIONS,POST,GET,PUT'"
      AllowHeaders: "'Content-Type,Authorization'"
      AllowOrigin: "'*'"

Resources:
  UtilsLayer:
    Type: AWS::Serverless::LayerVersion
    Properties:
      ContentUri: ../layers/utilLayer
      CompatibleRuntimes:
        - python3.9
    Metadata:
      BuildMethod: python3.9

  MessageLayer:
    Type: AWS::Serverless::LayerVersion
    Properties:
      ContentUri: ../layers/messageLayer
      CompatibleRuntimes:
        - python3.9
    Metadata:
      BuildMethod: python3.9

  NetworkApi:
    Type: AWS::Serverless::Api
    Properties:
      StageName: !Ref Stage
      Name: NetworkApi
      Description: Network Service
      Auth:
        AddDefaultAuthorizerToCorsPreflight: false
        DefaultAuthorizer: LambdaTokenAuthorizer
        Authorizers:
          LambdaTokenAuthorizer:
            FunctionArn: !Ref AuthorizerLambdaArn
      AccessLogSetting:
        DestinationArn: !Ref AccessLogArn
        Format: '{
          "requestTime":"$context.requestTime","requestId":"$context.requestId","httpMethod":"$context.httpMethod", "path":"$context.path", "resourcePath":"$context.resourcePath", "status":"$context.status", "responseLatency":"$context.responseLatency",
          "integrationRequestId":"$context.integration.requestId", "functionResponseStatus":"$context.integration.status", "authorizeResultStatus":"$context.authorize.status", "authorizerServiceStatus":"$context.authorizer.status",
          "authorizerRequestId":"$context.authorizer.requestId","authorizeError":"$context.authorize.error", "claims": "$context.authorizer.claims",
          "ip":"$context.identity.sourceIp", "userAgent":"$context.identity.userAgent", "principalId":"$context.authorizer.principalId", "cognitoUser":"$context.identity.cognitoIdentityId", "user":"$context.identity.user",
          "apiId":"$context.apiId"
        }'

  LambdaRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - lambda.amazonaws.com
            Action: sts:AssumeRole
      Path: /
      Policies:
        - PolicyName: caregem-secret-manager-lambda-policy
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: Allow
                Action:
                  - secretsmanager:GetSecretValue
                  - secretsmanager:PutSecretValue
                  - secretsmanager:DescribeSecret
                  - secretsmanager:TagResource
                  - secretsmanager:ListSecrets
                Resource: '*'
        - PolicyName: caregem-cognito-lambda-policy
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: Allow
                Action:
                  - cognito-idp:CreateUserPoolClient
                  - cognito-idp:CreateUserPoolClient
                  - cognito-idp:AdminConfirmSignUp
                  - cognito-idp:AdminInitiateAuth
                  - cognito-idp:AdminDeleteUser
                  - cognito-idp:AdminCreateUser
                  - cognito-idp:AdminSetUserPassword
                  - cognito-idp:AdminGetUser
                  - cognito-idp:AdminAddUserToGroup
                Resource: '*'
        - PolicyName: caregem-dynamodb-policy
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: Allow
                Action:
                  - dynamodb:GetItem
                  - dynamodb:DeleteItem
                  - dynamodb:PutItem
                  - dynamodb:Scan
                  - dynamodb:Query
                  - dynamodb:UpdateItem
                  - dynamodb:BatchWriteItem
                  - dynamodb:BatchGetItem
                  - dynamodb:DescribeTable
                  - dynamodb:ConditionCheckItem
                Resource: '*'
        - PolicyName: SNSPolicy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - 'SNS:ListTopic'
                Resource: ['*']
        - PolicyName: caregem-sns-policy
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: Allow
                Action:
                  - 'sns:Publish'
                Resource: '*'
        - PolicyName: caregem-s3-lambda-policy
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: Allow
                Action:
                  - s3:GetObject
                Resource: 'arn:aws:s3:::*'
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSLambdaVPCAccessExecutionRole

  NetworkUpdateCaregiverNetwork:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: Network-Update-Caregiver-Network
      CodeUri: ./
      Handler: update_caregiver_network.lambda_handler
      Layers:
        - !Ref UtilsLayer
      Role: !GetAtt LambdaRole.Arn
      Events:
        UpdCareGiverNetwork:
          Type: Api
          Properties:
            Path: /network/caregiver_update/{caregiver_id}
            Method: POST
            RestApiId: !Ref NetworkApi

  NetworkUpdatePatientNetwork:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: Network-Update-Patient-Network
      CodeUri: ./
      Handler: update_patient_networks.lambda_handler
      Layers:
        - !Ref UtilsLayer
        - !Ref MessageLayer
      Role: !GetAtt LambdaRole.Arn
      Events:
        UpdPatientNetwork:
          Type: Api
          Properties:
            Path: /network/patient_update/{patient_id}
            Method: POST
            RestApiId: !Ref NetworkApi
      Environment:
        Variables:
          ENVIRONMENT: !Ref Stage
          BUCKET_NAME: !Ref CaregemS3Config
          S3_FILE_NAME: caregem_urls.json
          ENCRYPTION_KEY_SECRET_ID: !Ref MessageSecret
          USE_TWILIO: !Ref UseTwilio
          SMS_ENABLED: !Ref TwilioSMSEnabled

  NetworkUserNetworkCrud:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: Network-User-Network-Crud-Lambda
      CodeUri: ./
      Handler: user_network.lambda_handler
      Layers:
        - !Ref UtilsLayer
        - !Ref MessageLayer
      Role: !GetAtt LambdaRole.Arn
      Events:
        GetUserNetwork:
          Type: Api
          Properties:
            Path: /network/networks/{user_id}
            Method: GET
            RestApiId: !Ref NetworkApi
        UpdatePatientNetwork:
          Type: Api
          Properties:
            Path: /network/patient/{patient_id}
            Method: PUT
            RestApiId: !Ref NetworkApi
        UpdateCaregiverNetwork:
          Type: Api
          Properties:
            Path: /network/caregiver/{caregiver_id}
            Method: PUT
            RestApiId: !Ref NetworkApi
      Environment:
        Variables:
          ENVIRONMENT: !Ref Stage
          BUCKET_NAME: !Ref CaregemS3Config
          S3_FILE_NAME: caregem_urls.json
          ENCRYPTION_KEY_SECRET_ID: !Ref MessageSecret
          USE_TWILIO: !Ref UseTwilio
          SMS_ENABLED: !Ref TwilioSMSEnabled

Outputs:
  NetworkApi:
    Description: 'API Gateway endpoint URL for NonProd stage for Network Service'
    Value: !Sub 'https://${NetworkApi}.execute-api.${AWS::Region}.amazonaws.com/${Stage}'
