version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "message-service"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-1fijtwp6d3ksr"
s3_prefix = "message-service"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
disable_rollback = true
parameter_overrides = "PrivateSubnets=\"/caregem/VpcSubnet\" LambdaSecurityGroupId=\"/caregem/VpcSg\" AuthorizerLambdaArn=\"/caregem/AuthorizerLambdaArn\" Stage=\"/caregem/Stage\" CognitoUserPool=\"/caregem/CognitoUserPool\" AwsRegion=\"/caregem/AwsRegion\" UserProfileTableName=\"/caregem/UserProfileTableName\" MysqlSecret=\"/caregem/MysqlSecret\" MlprepMysqlSecret=\"/caregem/MlprepMysqlSecret\" ChimeInstanceArn=\"/caregem/ChimeInstanceArn\" AccessLogArn=\"/caregem/AccessLogArn\" MessageSecret=\"/caregem/MessageSecret\" ChimePSTNNumber=\"/caregem/ChimePSTNNumber\" WebSocketURL=\"/caregem/WebSocketURL\""
image_repositories = []
