AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: SAM Template for SES Identities

Resources:
  CaregemDomainIdentity:
    Type: AWS::SES::EmailIdentity
    Properties:
      DkimAttributes:
        SigningEnabled: true
      DkimSigningAttributes:
        NextSigningKeyLength: RSA_2048_BIT
      EmailIdentity: caregem.org
      FeedbackAttributes:
        EmailForwardingEnabled: true
      MailFromAttributes: MailFromAttributes
