version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "user-service"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-1fijtwp6d3ksr"
s3_prefix = "user-service"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
parameter_overrides = "PrivateSubnets=\"/caregem/VpcSubnet\" LambdaSecurityGroupId=\"/caregem/VpcSg\" AuthorizerLambdaArn=\"/caregem/AuthorizerLambdaArn\" Stage=\"/caregem/Stage\" CognitoUserPool=\"/caregem/CognitoUserPool\" AwsRegion=\"/caregem/AwsRegion\" UserProfileTableName=\"/caregem/UserProfileTableName\" MysqlSecret=\"/caregem/MysqlSecret\" MlprepMysqlSecret=\"/caregem/MlprepMysqlSecret\" AccessLogArn=\"/caregem/AccessLogArn\" CognitoSecret=\"/caregem/CognitoSecret\" MessageSecret=\"/caregem/MessageSecret\" EmailSource=\"/caregem/EmailSource\" EmailSourceArn=\"/caregem/EmailSourceArn\" DestinationEmailList=\"/caregem/DestinationEmailList\" SftpSecretName=\"/caregem/SftpSecretName\""
image_repositories = []
disable_rollback = true