AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  medication-service

  SAM Template for medication-service

Parameters:
  PrivateSubnets:
    Type: 'AWS::SSM::Parameter::Value<List<String>>'
    Default: /caregem/VpcSubnet
  LambdaSecurityGroupId:
    Type: 'AWS::SSM::Parameter::Value<String>'
    Default: /caregem/VpcSg
  AuthorizerLambdaArn:
    Type: 'AWS::SSM::Parameter::Value<String>'
    Default: /caregem/AuthorizerLambdaArn
  Stage:
    Type: 'AWS::SSM::Parameter::Value<String>'
    Default: /caregem/Stage
  CognitoUserPool:
    Type: 'AWS::SSM::Parameter::Value<String>'
    Default: /caregem/CognitoUserPool
  AwsRegion:
    Type: 'AWS::SSM::Parameter::Value<String>'
    Default: /caregem/AwsRegion
  UserProfileTableName:
    Type: 'AWS::SSM::Parameter::Value<String>'
    Default: /caregem/UserProfileTableName
  MysqlSecret:
    Type: 'AWS::SSM::Parameter::Value<String>'
    Default: /caregem/MysqlSecret
  MlprepMysqlSecret:
    Type: 'AWS::SSM::Parameter::Value<String>'
    Default: /caregem/MlprepMysqlSecret
  AccessLogArn:
    Type: 'AWS::SSM::Parameter::Value<String>'
    Default: /caregem/AccessLogArn
  MessageSecret:
    Type: 'AWS::SSM::Parameter::Value<String>'
    Default: /caregem/MessageSecret

Globals:
  Function:
    Timeout: 5
    MemorySize: 512
    Runtime: python3.9
    Architectures:
      - x86_64
    VpcConfig:
      SecurityGroupIds:
        - !Ref LambdaSecurityGroupId
      SubnetIds: !Ref PrivateSubnets
    Environment:
      Variables:
        LOG_LEVEL: 'INFO'
        DB_SECRET_NAME: !Ref MysqlSecret
        MLPREP_SECRET_NAME: !Ref MlprepMysqlSecret
        DYNAMODB_REGION: !Ref AwsRegion
        AWSREGION: !Ref AwsRegion
        USER_POOL_REGION: !Ref AwsRegion
        USER_PROFILE_TABLE_NAME: !Ref UserProfileTableName
        USER_POOL_ID: !Ref CognitoUserPool
  Api:
    EndpointConfiguration: REGIONAL
    TracingEnabled: true
    OpenApiVersion: '2.0'
    Cors:
      AllowMethods: "'OPTIONS,POST,GET,PUT'"
      AllowHeaders: "'Content-Type,Authorization'"
      AllowOrigin: "'*'"

Resources:
  UtilsLayer:
    Type: AWS::Serverless::LayerVersion
    Properties:
      ContentUri: ../layers/utilLayer
      CompatibleRuntimes:
        - python3.9
    Metadata:
      BuildMethod: python3.9

  Api:
    Type: AWS::Serverless::Api
    Properties:
      StageName: !Ref Stage
      Name: Medication Api
      Description: Medication Service
      Auth:
        AddDefaultAuthorizerToCorsPreflight: false
        DefaultAuthorizer: LambdaTokenAuthorizer
        Authorizers:
          LambdaTokenAuthorizer:
            FunctionArn: !Ref AuthorizerLambdaArn
      AccessLogSetting:
        DestinationArn: !Ref AccessLogArn
        Format: '{
          "requestTime":"$context.requestTime","requestId":"$context.requestId","httpMethod":"$context.httpMethod", "path":"$context.path", "resourcePath":"$context.resourcePath", "status":"$context.status", "responseLatency":"$context.responseLatency",
          "integrationRequestId":"$context.integration.requestId", "functionResponseStatus":"$context.integration.status", "authorizeResultStatus":"$context.authorize.status", "authorizerServiceStatus":"$context.authorizer.status",
          "authorizerRequestId":"$context.authorizer.requestId","authorizeError":"$context.authorize.error", "claims": "$context.authorizer.claims",
          "ip":"$context.identity.sourceIp", "userAgent":"$context.identity.userAgent", "principalId":"$context.authorizer.principalId", "cognitoUser":"$context.identity.cognitoIdentityId", "user":"$context.identity.user",
          "apiId":"$context.apiId"
        }'

  LambdaRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - lambda.amazonaws.com
            Action: sts:AssumeRole
      Path: /
      Policies:
        - PolicyName: caregem-secret-manager-lambda-policy
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: Allow
                Action:
                  - secretsmanager:GetSecretValue
                Resource: '*'
        - PolicyName: caregem-dynamodb-policy
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: Allow
                Action:
                  - dynamodb:GetItem
                  - dynamodb:PutItem
                  - dynamodb:Scan
                  - dynamodb:Query
                  - dynamodb:BatchGetItem
                Resource: '*'
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSLambdaVPCAccessExecutionRole

  MedicationCodeValuesFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: Medication-Code-Values-Lambda
      CodeUri: ./
      Handler: med_code_values.lambda_handler
      Layers:
        - !Ref UtilsLayer
      Role: !GetAtt LambdaRole.Arn
      Events:
        MedSig:
          Type: Api
          Properties:
            Path: /medication/sig
            Method: GET
            RestApiId: !Ref Api
        MedReasons:
          Type: Api
          Properties:
            Path: /medication/medreasons
            Method: GET
            RestApiId: !Ref Api
        MedUnit:
          Type: Api
          Properties:
            Path: /medication/unit
            Method: GET
            RestApiId: !Ref Api
        MedInfoFrom:
          Type: Api
          Properties:
            Path: /medication/info_from
            Method: GET
            RestApiId: !Ref Api
        MedDuration:
          Type: Api
          Properties:
            Path: /medication/duration
            Method: GET
            RestApiId: !Ref Api
        MedDiscontinueReason:
          Type: Api
          Properties:
            Path: /medication/discontinue
            Method: GET
            RestApiId: !Ref Api

  MedicationHistoryFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: Medication-History-Lambda
      CodeUri: ./
      Handler: med_history.lambda_handler
      Layers:
        - !Ref UtilsLayer
      Role: !GetAtt LambdaRole.Arn
      Events:
        MedHistory:
          Type: Api
          Properties:
            Path: /medication/drughistory/{patient_id}/{rxcui_id}
            Method: GET
            RestApiId: !Ref Api
      Environment:
        Variables:
          RXCUIS_URL: https://rxnav.nlm.nih.gov/REST/rxcui/{rxcui}/historystatus.json
          CLINICALTABLES_URL: https://clinicaltables.nlm.nih.gov/api/rxterms/v3/search?ef=STRENGTHS_AND_FORMS,RXCUIS&terms=

  MedicationDupCheckFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: Medication-DupCheck-Lambda
      CodeUri: ./
      Handler: med_dup_check.lambda_handler
      Layers:
        - !Ref UtilsLayer
      Role: !GetAtt LambdaRole.Arn
      Events:
        MedDupCheck:
          Type: Api
          Properties:
            Path: /medication/dupcheck/{patient_id}/{rxcui_id}
            Method: GET
            RestApiId: !Ref Api
      Environment:
        Variables:
          RXCUIS_URL: https://rxnav.nlm.nih.gov/REST/rxcui/{rxcui}/historystatus.json
          CLINICALTABLES_URL: https://clinicaltables.nlm.nih.gov/api/rxterms/v3/search?ef=STRENGTHS_AND_FORMS,RXCUIS&terms=

  MedicationListFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: Medication-Listing-Lambda
      CodeUri: ./
      Handler: list_medication.lambda_handler
      Layers:
        - !Ref UtilsLayer
      Role: !GetAtt LambdaRole.Arn
      Events:
        MedActiveList:
          Type: Api
          Properties:
            Path: /medication/listactivemedication/{patient_id+}
            Method: GET
            RestApiId: !Ref Api
        MedInActiveList:
          Type: Api
          Properties:
            Path: /medication/liststoppedmedication/{patient_id+}
            Method: GET
            RestApiId: !Ref Api

  MedicationFindFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: Medication-FindMed-Lambda
      CodeUri: ./
      Handler: find_med_webservice.lambda_handler
      Layers:
        - !Ref UtilsLayer
      Role: !GetAtt LambdaRole.Arn
      Events:
        MedProductList:
          Type: Api
          Properties:
            Path: /medication/listproductnames
            Method: GET
            RestApiId: !Ref Api
      Environment:
        Variables:
          RXCUIS_URL: https://rxnav.nlm.nih.gov/REST/rxcui/{rxcui}/historystatus.json
          CLINICALTABLES_URL: https://clinicaltables.nlm.nih.gov/api/rxterms/v3/search?ef=STRENGTHS_AND_FORMS,RXCUIS&terms=

  MedicationSaveFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: Medication-Save-Lambda
      CodeUri: ./
      Handler: med_save.lambda_handler
      Layers:
        - !Ref UtilsLayer
      Role: !GetAtt LambdaRole.Arn
      Events:
        MedSave:
          Type: Api
          Properties:
            Path: /medication/save/{patient_id}
            Method: POST
            RestApiId: !Ref Api
        MedStop:
          Type: Api
          Properties:
            Path: /medication/stop/{patient_id}/{product_id}
            Method: PUT
            RestApiId: !Ref Api
        MedDelete:
          Type: Api
          Properties:
            Path: /medication/delete/{med_id}
            Method: PUT
            RestApiId: !Ref Api
      Environment:
        Variables:
          ENCRYPTION_KEY_SECRET_ID: !Ref MessageSecret
         
Outputs:
  MedicationApi:
    Description: 'API Gateway endpoint URL for NonProd stage for Medication Service'
    Value: !Sub 'https://${Api}.execute-api.${AWS::Region}.amazonaws.com/${Stage}'
